# =============================================================================
# Kubernetes Service
# =============================================================================
# File        : ms-transaction-orchestrator-service.yaml
# Project     : MSIMPL - Microservices Platform
# Service     : ms-transaction-orchestrator
# Namespace   : msimpl
# Purpose     : Exposes the Transaction Orchestrator microservice within the
#               Kubernetes cluster using a ClusterIP Service.
# Version     : 1.0.0
# =============================================================================
#
# Notes
# -----
# - Internal service accessible only within the Kubernetes cluster.
# - Uses Kubernetes DNS for service discovery.
# - Compatible with GitHub Actions, Argo CD and AWS EKS.
#
# =============================================================================

apiVersion: v1
kind: Service

metadata:

  name: ms-transaction-orchestrator

  namespace: msimpl

  labels:
    app: ms-transaction-orchestrator

spec:

  type: ClusterIP

  selector:
    app: ms-transaction-orchestrator

  ports:

    - protocol: TCP

      port: 8082

      targetPort: 8082