# =============================================================================
# Kubernetes Ingress
# =============================================================================
# File        : ingress.yaml
# Project     : MSIMPL - Microservices Platform
# Namespace   : msimpl
# Purpose     : Exposes MSIMPL microservices through the NGINX Ingress
#               Controller for local development.
# Version     : 1.0.0
# =============================================================================
#
# Notes
# -----
# - Requires the NGINX Ingress Controller.
# - Routes external HTTP requests to internal ClusterIP Services.
# - Compatible with GitHub Actions, Argo CD and AWS EKS.
#
# =============================================================================

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: msimpl-ingress
  namespace: msimpl

spec:
  ingressClassName: nginx

  rules:

    - host: localhost

      http:

        paths:

          - path: /transaction
            pathType: Prefix
            backend:
              service:
                name: ms-transaction-orchestrator
                port:
                  number: 8082

          - path: /wallet
            pathType: Prefix
            backend:
              service:
                name: ms-wallet
                port:
                  number: 8080

          - path: /notification
            pathType: Prefix
            backend:
              service:
                name: ms-notification
                port:
                  number: 8081