apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Environment-independent resources
resources:
  - deployment.yaml
  - service.yaml

# Common labels applied to all resources
commonLabels:
  app: ms-transaction-orchestrator
  tier: backend

# Optional: prefix to distinguish base resources
#namePrefix: base-
