# =============================================================================
# Kubernetes Deployment
# =============================================================================
# File        : deployment.yaml
# Project     : MSIMPL - Microservices Platform
# Service     : ms-notification
# Namespace   : msimpl
# Purpose     : Deploy the Notification microservice
# Version     : 1.0.0
# =============================================================================
#
# Notes
# -----
# - Uses ConfigMaps and Secrets for externalized configuration.
# - Configured for local Kind Kubernetes.
# - Compatible with GitHub Actions, Argo CD and AWS EKS.
#
# =============================================================================

apiVersion: apps/v1
kind: Deployment

metadata:
  name: ms-notification
  namespace: msimpl

  labels:
    app: ms-notification

spec:

  replicas: 1

  selector:
    matchLabels:
      app: ms-notification

  template:

    metadata:
      labels:
        app: ms-notification

    spec:

      containers:

        - name: ms-notification

          image: sanjeev777/msimpl_dochub:ms-notification-1.0

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8081

          envFrom:

            - configMapRef:
                name: msimpl-common-config

            - configMapRef:
                name: ms-notification-db-config

            - configMapRef:
                name: msimpl-kafka-config

            - configMapRef:
                name: msimpl-observability-config

            - secretRef:
                name: msimpl-secret

          resources:

            requests:
              cpu: "200m"
              memory: "384Mi"

            limits:
              cpu: "500m"
              memory: "768Mi"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3