# ==========================================================
# Kubernetes ConfigMap
# File      : ms-wallet-db-config.yaml
# Project   : MSIMPL - Microservices Platform
# Author    : Sanjeev Kumar
#
# Description
# -----------
# Stores non-sensitive database configuration for the
# MS Wallet microservice.
#
# Purpose
# -------
# - Database Host
# - Database Port
# - Database Name
#
# Notes
# -----
# - Database username and password must NOT be stored here.
# - Sensitive database credentials are stored in
#   Kubernetes Secrets.
# - Spring Boot reads these values through environment
#   variables defined in application-db.yml.
#
# ==========================================================

apiVersion: v1
kind: ConfigMap

metadata:
  name: ms-wallet-db-config
  namespace: msimpl

  labels:
    app.kubernetes.io/name: ms-wallet
    app.kubernetes.io/component: database-config
    app.kubernetes.io/part-of: microservices-platform

data:

  # --------------------------------------------------------
  # PostgreSQL Connection
  # --------------------------------------------------------
  DB_HOST: "host.docker.internal"

  DB_PORT: "5432"

  DB_NAME: "wallet_db"