# =============================================================================
# Kubernetes Deployment
# =============================================================================
# File        : deployment.yaml
# Project     : MSIMPL - Microservices Platform
# Service     : ms-wallet
# Namespace   : msimpl
# Purpose     : Deploy the Wallet microservice
# Version     : 1.0.0
# =============================================================================
#
# Notes
# -----
# - Uses ConfigMaps and Secrets for externalized configuration.
# - Configured for local Kind Kubernetes.
# - Compatible with GitHub Actions, Argo CD and AWS EKS.
#
# =============================================================================

apiVersion: apps/v1
kind: Deployment

metadata:
  name: ms-wallet
  namespace: msimpl

  labels:
    app: ms-wallet

spec:

  replicas: 1

  selector:
    matchLabels:
      app: ms-wallet

  template:

    metadata:
      labels:
        app: ms-wallet

    spec:

      containers:

        - name: ms-wallet

          image: sanjeev777/msimpl_dochub:ms-wallet-1.0

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          envFrom:

            - configMapRef:
                name: msimpl-common-config

            - configMapRef:
                name: ms-wallet-db-config

            - configMapRef:
                name: msimpl-kafka-config

            - configMapRef:
                name: msimpl-observability-config

            - secretRef:
                name: msimpl-secret

          resources:

            requests:
              cpu: "200m"
              memory: "384Mi"

            limits:
              cpu: "500m"
              memory: "768Mi"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3